apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --chart
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: blackbox
  name: blackbox
spec:
  ports:
    - name: "9115"
      port: 9115
      targetPort: 9115
  selector:
    io.kompose.service: blackbox
