apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --chart
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.EXTERNAL_PORT }}
      targetPort: 3000
  externalIPs:
    - {{ .Values.EXTERNAL_IP }}
  selector:
    io.kompose.service: grafana
