apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --chart
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  type: LoadBalancer
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  externalIPs:
    - 192.168.11.133
  selector:
    io.kompose.service: grafana
